### ISSUE TITLE
ld: framework 'DatadogObjc' not found during linkDebugFrameworkIosArm64 task in KMM iOS framework

### ISSUE THREAD

**Issue by etilly** [DataDog/dd-sdk-kotlin-multiplatform#94]
### Question

Hello,

We recently integrated the Datadog SDK into our Kotlin Multiplatform Mobile (KMM) project. When generating the iOS framework using the `embedAndSignAppleFrameworkForXcode` task, we encounter the following error :

![Image](https://github.com/user-attachments/assets/8b75645b-10ab-4100-8a45-ea4b67840028)

Despite these efforts, the issue persists.

Do you have any insights on how to resolve this?

Thank you in advance for your help.

**Comment by 0xnm** [comment]
Hello @etilly!

`DatadogObjc` should be added to the Frameworks list in the XCode (since you are using `embedAndSignAppleFrameworkForXCode`.

![Image](https://github.com/user-attachments/assets/6e28a9c9-feee-4e56-adbf-5b9e14c59c46)

If you have it added there and problem still persists, can you please share with us more details: what is the Kotlin version you are using, what is your build script, etc.?

**Comment by etilly** [comment]
Thanks for your feedback,

I managed to fix my problem.

This was due to the architecture of my application which was built in modules.

I had to merge my modules which use my shared framework into the main target of the application to then be able to correctly use the gradle task `embedAndSignAppleFrameworkForXCode`

**Comment by carlos-prezzee** [comment]
@etilly 
Curious on what you did to solve this issue - running into the same one.
When you said merge your modules. Are your referring to SPM modules on the iOS side right?

**Comment by 0xnm** [comment]
@carlos-prezzee Did you manage to solve your integration issue? If not, you can post your setup details and we will look into the solution.

**Comment by etilly** [comment]
@carlos-prezzee, 

Sorry for the late reply,

Before I had an architecture with static frameworks with several targets.

For example, I had these targets:

MainApp (main target)
Environment
Data
Domain
Presentation

And my targets Data, Domain and Presentation had a dependency with my KMM framework.

So, I had to migrate everything to my main target (MainApp) to have only one target with a single dependency on my KMM framework

**Comment by carlos-prezzee** [comment]
thanks @etilly 
Got a similar setup and I got the same error as you got.
I don't have a pet project at hand but It should be able to reproduce it by following @etilly setup (Thats what we have too)

**Comment by menjoo** [comment]
We had the same issue. Our module where we use the DataDog SDK is a dynamic module and it's used by a static module. Managed to fix the build error by adding this to the module's config:
```kotlin
// Disable the iOS framework linking tasks, linking will happen later.
// Needed to prevent build error `ld: framework 'DatadogObjc' not found`
tasks.configureEach {
    if (name.contains("linkDebugFrameworkIos") || name.contains("linkReleaseFrameworkIos")) {
        enabled = false
    }
}
```

**Comment by gustavaa** [comment]
We are experiencing the same issue and unfortunately none of work-arounds above work for us.

We have a single module iOS app that have a dependency on our KMP framework that is also configured as an umbrella framework with a dependency on a shared core module that uses datadog. So the dependency tree looks like this: iOS App -> KMP app framework -> Generic core KMP framework shared with other app frameworks (using datadog).

If we use the suggested work-around above with disabling the linking tasks, we get a bunch of `Undefined symbol` errors. If we don't use it, we get the `ld: framework 'DatadogObjc' not found` error. Could you consider reopening this issue?

**Comment by gustavaa** [comment]
I created a sample project where this issue is reproducible: https://github.com/gustavaa/datadog-xcframework-issue/blob/main/composeApp/build.gradle.kts

It seems to be related to creating an XCFramework. In the sample project, the issue can be solved simply by changing `xcFramework.add(this)` in :composeApp `build.gradle` to `isStatic = true`. Unfortunately, this is not a solution for our production project as we need the XCFramework output.
