### ISSUE TITLE
Failed resolution of: Ljava/time/Instant on devices with Android 7.1.1, 7.0, 6.0

### ISSUE THREAD

**Issue by gros83** [DataDog/dd-sdk-kotlin-multiplatform#96]
### Stack trace

Hello,

We recently integrated the Datadog SDK into our Kotlin Multiplatform Mobile (KMM) project. On devices with Android 7.1.1, 7.0, 6.0 we encounter an error like this:
![Image](https://github.com/user-attachments/assets/40ecc90b-5acf-4402-afb9-5dc0798ee68c)

### Volume

0.0363

### Affected SDK versions

0.0.2

### Latest working SDK version

0.0.2

### Does the crash manifest in the latest SDK version?

Yes

### Kotlin version

2.0.0

### Gradle / AGP version

8.6/8.4.1

### iOS Integration Methods

None

### Other dependencies versions

Ktor 2.3.11

**Comment by 0xnm** [comment]
Hello @gros83!

Thanks for reporting it, we are looking for the solution. The issue is caused by the fact that this class is available only since Android API 26.

Also I noticed that you are using Kotlin 2.0.0, but Kotlin 2.0.20 is required if you enabled crash tracking on iOS (a bit of details [here](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/setup/kotlin-multiplatform/#add-native-dependencies-for-ios)), but anyway it is not connected to the issue reported.

**Comment by 0xnm** [comment]
@gros83 We've made release [0.0.3](https://github.com/DataDog/dd-sdk-kotlin-multiplatform/releases/tag/0.0.3) which contains the necessary fix and some new functionality as well. Can you try it out and if issue is still there, then re-open this ticket?
